config/routes.rb
Rails.application.routes.draw do
  controller :session do
    get '/login', to: 'session#login'
    post '/session/create', to: 'session#create'
    get '/logout', to: 'session#logout'
  end

  resources :users do
    get '/notifications', to: 'notification#index', as: 'notifications'
  end

  resources :projects do
    resources :assets do
      member do
        put '/ship', to: 'assets#ship', as: 'ship'
        get '/add-files', to: 'assets#add_files'
        put '/upload', to: 'assets#upload'
      end
      resources :comments
    end
    resources :invitations do
      member do
        get '/accept', to: 'invitations#accept', as: 'accept'
      end
    end
  end


  controller 'dropbox' do
    get "/auth/dropbox_oauth2/callback", to: :link, as: :dropbox_oauth2_callback
    get "/dropbox/unlink", to: :unlink, as: :dropbox_unlink
  end

  controller 'github' do
    get "/auth/github/callback", to: :link, as: :github_oauth2_callback
    get "/github/unlink", to: :unlink, as: :github_unlink
  end

  controller 'notification' do
    get "/notification/:id/read", to: :read, as: 'notification_read'
  end

  root to: "projects#index"
end

app/controllers/session_controller.rb
class SessionController < ApplicationController
  skip_before_filter :ensure_authenticated, only: [:login, :create]
  def login
    @user = User.new
  end

  def create
    user = User.find_by_username!(login_params[:username])
    if user.authenticate(login_params[:password])
      session[:user_id] = user.id
      redirect_to user, flash: {notice: "Logged in."}
    else
      redirect_to login_path, flash: {notice: "Email or password is incorrect. Try again."}
    end
  rescue ActiveRecord::RecordNotFound
    redirect_to login_path, flash: {notice: "Email or password is incorrect. Try again."}
  end

  def logout
    reset_session
    redirect_to login_path, flash: {notice: "Logged out."}
  end

  private
  def login_params
    params.require(:user).permit(:username, :password)
  end
end

app/helpers/session_helper.rb
module SessionHelper
end

app/views/session/login.html.erb
<div class="skinny-container">
  <h3>Log In</h3>
  <%= form_for @user, url: session_create_path do |f| %>
    <div class="form-group glued">
      <%= f.text_field :username, class: "form-control", placeholder: "Username" %>
      <%= f.password_field :password, class: "form-control", placeholder: "Password" %>
    </div>
    <%= f.submit "Log In", class: "btn btn-success" %>
  <% end %>
</div>

app/views/session/logout.html.erb
<h1>Session#logout</h1>
<p>Find me in app/views/session/logout.html.erb</p>