config/routes.rb
Rails.application.routes.draw do
  controller :session do
    get '/login', to: 'session#login'
    post '/session/create', to: 'session#create'
    get '/logout', to: 'session#logout'
  end

  resources :users do
    get '/notifications', to: 'notification#index', as: 'notifications'
  end

  resources :projects do
    resources :assets do
      member do
        put '/ship', to: 'assets#ship', as: 'ship'
        get '/add-files', to: 'assets#add_files'
        put '/upload', to: 'assets#upload'
      end
      resources :comments
    end
    resources :invitations do
      member do
        get '/accept', to: 'invitations#accept', as: 'accept'
      end
    end
  end


  controller 'dropbox' do
    get "/auth/dropbox_oauth2/callback", to: :link, as: :dropbox_oauth2_callback
    get "/dropbox/unlink", to: :unlink, as: :dropbox_unlink
  end

  controller 'github' do
    get "/auth/github/callback", to: :link, as: :github_oauth2_callback
    get "/github/unlink", to: :unlink, as: :github_unlink
  end

  controller 'notification' do
    get "/notification/:id/read", to: :read, as: 'notification_read'
  end

  root to: "projects#index"
end

app/models/project.rb
class Project < ActiveRecord::Base
  has_many :assets
  has_and_belongs_to_many :users
  belongs_to :owner, class_name: "User"
  validates :name, :description, presence: true
  validates :homepage, format: /https?:\/\/[\S]+/i, allow_nil: true
  def create_folder(folder_name)
    owner.dropbox.file_create_folder("#{name.downcase.parameterize}/#{folder_name}")
  end

  validate :create_project_folder
  def create_project_folder
    begin
      owner.dropbox.file_create_folder(name.downcase.parameterize) unless Rails.env.test?
    rescue DropboxError => e
      puts e.message
      errors[:base] << "Failed to create dropbox folder."
    end
  end

  def has_member?(user)
    owner == user or users.include? user
  end

  def folder
    name.downcase.parameterize
  end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  include ApplicationHelper
  before_action :set_project, only: [:show, :edit, :update, :destroy]

  def index
    @projects = Project.all
  end

  def show
  end

  def new
    @project = Project.new
  end

  def edit
  end

  def create
    @project = Project.new(project_params)
    @project.users << current_user
    @project.owner = current_user

    if @project.save
      redirect_to @project, notice: 'Project was successfully created.'
    else
      render :new
    end
  end

  def update
    if @project.update(project_params)
      redirect_to @project, notice: 'Project was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @project.destroy
    redirect_to projects_url, notice: 'Project was successfully destroyed.'
  end

  private
    def set_project
      @project = Project.find(params[:id])
    end

    def project_params
      params.require(:project).permit(:name, :description)
    end
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/projects/_form.html.erb
<%= form_for(@project) do |f| %>
  <% if @project.errors.any? %>
    <div class="error-explanation well text-danger">
      <ul>
      <% @project.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="form-group glued">
    <%= f.text_field :name, class: "form-control", placeholder: "Project Name" %>
    <%= f.text_area :description, class: "form-control", placeholder: "Description", size: "24x6" %>
  </div>
  <%= f.submit class: "btn btn-success pull-right" %>
<% end %>
<div class="clearfix"></div>

app/views/projects/edit.html.erb
<h1>Editing project</h1>

<%= render 'form' %>

<%= link_to 'Show', @project %> |
<%= link_to 'Back', projects_path %>

app/views/projects/index.html.erb
<h1>Your Projects</h1>
<p class="text-muted">Use the sidebar menu to add a new project.</p>
<ul>
  <% current_user.projects.each do |project| %>
    <li><%=link_to project.name, project_path(project) %></li>
  <% end %>
</ul>

<h4> Pending Invites </h4>
<ul>
  <% current_user.invites.pending.each do |invite| %>
    <li><%= invite %></li>
  <% end %>
</ul>

app/views/projects/new.html.erb
<div class="page col-md-12">
  <div class="col-md-6">
  <h1>Create a Project:</h1>
  <%= render 'form' %>
  </div>
</div>

app/views/projects/show.html.erb
<section class="page col-md-12">
  <h1><%= @project.name %> <small class="text-muted">Project</small></h1>
  <p class="text-muted"><em><%= @project.description %></em></p>
  <div class="action-menu">
    <%= link_to new_project_asset_path(@project), class: "btn btn-primary" do %>
      <span class="glyphicon glyphicon-plus"></span>
      New Asset
    <% end %>
  </div>
  <div class="staged-assets js-masonry" data-masonry-options='{ "columnWidth" : 25%, "itemSelector" :  }'>
    <% @project.assets.staged.each do |asset| %>
      <%= render "assets/asset_widget", project: @project, asset: asset %>
    <% end %>
  </div>
  <div class="collaborators">
    <p class="text-muted">Collaborators</p>
      <% @project.users.each do |user| %>
        <%= image_tag user.gravatar_url(25), title: user.username %>
      <% end %>
      <%= link_to new_project_invitation_path @project do %>
        <span class="glyphicon glyphicon-plus"></span>
      <% end %>
    </div>

</section>