config/routes.rb
Rails.application.routes.draw do
  controller :session do
    get '/login', to: 'session#login'
    post '/session/create', to: 'session#create'
    get '/logout', to: 'session#logout'
  end

  resources :users do
    get '/notifications', to: 'notification#index', as: 'notifications'
  end

  resources :projects do
    resources :assets do
      member do
        put '/ship', to: 'assets#ship', as: 'ship'
        get '/add-files', to: 'assets#add_files'
        put '/upload', to: 'assets#upload'
      end
      resources :comments
    end
    resources :invitations do
      member do
        get '/accept', to: 'invitations#accept', as: 'accept'
      end
    end
  end


  controller 'dropbox' do
    get "/auth/dropbox_oauth2/callback", to: :link, as: :dropbox_oauth2_callback
    get "/dropbox/unlink", to: :unlink, as: :dropbox_unlink
  end

  controller 'github' do
    get "/auth/github/callback", to: :link, as: :github_oauth2_callback
    get "/github/unlink", to: :unlink, as: :github_unlink
  end

  controller 'notification' do
    get "/notification/:id/read", to: :read, as: 'notification_read'
  end

  root to: "projects#index"
end

app/models/asset.rb
class Asset < ActiveRecord::Base
  attr_accessor :files, :thumbnail
  belongs_to :project
  has_many :comments
  validates :name, presence: true, uniqueness: true
  enum state: ['staged', 'shipped', 'abandoned']
  before_create :create_asset_folder

  def create_asset_folder
    begin
      project.create_folder(name.downcase.parameterize) unless Rails.env.test?
    rescue DropboxError => e
      puts e.message
      errors[:base] << "Failed to create asset folder in dropbox"
    end
  end

  def files
    return @files unless @files.nil?

    @files = []
    metadata = dropbox.metadata asset_folder, 1000, true

    metadata["contents"].each do |file|
      asset_file = AssetFile.new file["path"]
      asset_file.asset = self
      if asset_file.filename == "_thumb"
        @thumbnail = asset_file
      else
        @files.push asset_file
      end
    end

    @files
  end

  def thumbnail
    @thumbnail || files
    @thumbnail
  end

  def ship!
    #GITHUB STUFF GOES HERR
    shipped!
    save!
  end

  def abandon!
    abandoned!
    save!
  end

  def shipable?
    not experimental? && staged?
  end

  def dropbox
    project.owner.dropbox
  end

  private
  def asset_folder
    "#{project.folder}/#{name.downcase.parameterize}"
  end
end

app/controllers/assets_controller.rb
class AssetsController < ApplicationController
  before_action :set_asset, only: [:show, :edit, :update, :destroy, :add_files, :upload]
  before_action :set_project
  before_action :set_new_comment, only: :show

  def index
    @assets = Asset.all
  end

  def show
  end

  def new
    @asset = Asset.new
  end

  def edit
  end

  def create
    @asset = Asset.new(asset_params)
    @asset.project = @project
    if @asset.save
      redirect_to project_asset_path(@project, @asset), notice: 'Asset was successfully created.'
    else
      render :new
    end
  end

  def update
    if @asset.update(asset_params)
      redirect_to project_asset_path(@project, @asset), notice: 'Asset was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @asset.destroy
    redirect_to project_assets_url(@project), notice: 'Asset was successfully destroyed.'
  end

  def upload
    uploader = @asset.dropbox.get_chunked_uploader(asset_params[:upload], asset_params[:upload].size)
    uploader.upload
    uploader.finish("#{@asset.folder_name}/#{asset_params[:upload].original_filename}", true)
    @asset.files = nil # clear the cached model.
    render json: { created: true }
  end

  def files
  end

  private
    def set_asset
      @asset = Asset.find(params[:id])
    end

    def set_project
      @project = Project.find(params[:project_id])
    end

    def set_new_comment
      @new_comment = Comment.new
      @new_comment.asset = @asset
    end

    def asset_params
      params.require(:asset).permit(:name, :experimental, :upload)
    end
end

app/helpers/assets_helper.rb
module AssetsHelper
end

app/views/assets/_asset_widget.html.erb
<div class='widget'>
  <%= link_to project_asset_path(project, asset), class: "col-md-4 col-lg-3 col-sm-2 col-xs-1" do %>
    <% if asset.thumbnail.nil? %>
      <div class="thumb">
      </div>
    <% else %>
      <%= image_tag asset.thumbnail.display_image_path, class: "thumb" %>
    <% end %>
  <div class="info">
    <h1><%= asset.name %></h1>
    <p>
      <small class="text-muted">
        <span class="glyphicon glyphicon-folder-open"></span>
        &nbsp; <%= asset.files.count %> Files
      </small>
    </p>
  </div>
<% end %>
</div>

app/views/assets/_comment.html.erb
<% if comment.out_of_date? %>
  <div class="comment collapsed">
    <p class="text-muted">
      <strong>
        <span class="glyphicon glyphicon-time"></span> &nbsp; <%= comment.commenter.username %>
      </strong>
      commented on an our of date revision.
    </p>
  </div>
<% else %>
  <div class="comment">
    <div class="comment-header">
      <%= image_tag comment.commenter.gravatar_url(40), class: "pull-left" %>
      <p><small class="text-muted">@<%= comment.commenter.username %> commented <%= time_ago_in_words(comment.updated_at) %> ago: </small>
      </div>
    <div class="body"> <%= comment.body.html_safe %> </div>
  </div>
<% end %>

app/views/assets/_form.html.erb
<%= form_for [@project, @asset] do |f| %>
  <% if @asset.errors.any? %>
    <div class="error_explanation well text-danger">
      <h2><%= pluralize(@asset.errors.count, "error") %> prohibited this asset from being saved:</h2>

      <ul>
      <% @asset.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="form-group">
  <%= f.text_field :name, class: "form-control", placeholder: "Asset Name" %>
  </div>
  <div class="form-group">
    <%= f.check_box :experimental %>
    <strong> Experimental Mode </strong>
    <p class="text-muted">
      Use experimental mode for assets that you want feedback on, but dont want to ship right now.
      You cannot ship experimental assets until you mark them as non-experimental.
    </p>
  </div>
  <div class="actions">
    <%= f.submit class: "btn btn-success" %>
  </div>
<% end %>

app/views/assets/_new_comment_form.html.erb
<div class="new-comment-form">
<!-- Nav tabs -->
<ul class="nav nav-tabs">
  <li class="active"><a href="#write" data-toggle="tab">New Comment</a></li>
  <li><a href="#preview" data-toggle="tab">Preview</a></li>
</ul>

<!-- Tab panes -->
<div class="tab-content">
  <div class="tab-pane active" id="write">
  <%= form_for [comment.asset.project, comment.asset, comment] do |f| %>
    <div class="form-group">
      <%= f.text_area :body, rows: 6, cols: 80, class:"form-control" %>
    </div>
      <%= f.submit "Send", class: "btn btn-primary" %>
  <% end %>
  </div>
  <div class="tab-pane" id="preview">
    <strong class="text-muted"> Comming soon! </strong>
  </div>
</div>
</div>

app/views/assets/edit.html.erb
<h1>Editing asset</h1>

<%= render 'form' %>

<%= link_to 'Show', @asset %> |
<%= link_to 'Back', project_assets_path(@project) %>

app/views/assets/files.html.erb
<h1><%= @asset.name %></h1>
<h5>File manager</h5>

<p class="text-muted">You can upload files to your new asset here. To update a file, just upload it again and it will be overwritten.</p>

<div>Temporary. File uploader will go here</div>

app/views/assets/index.html.erb
<h1>Listing assets</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @assets.each do |asset| %>
      <tr>
        <td><%= link_to 'Show', asset %></td>
        <td><%= link_to 'Edit', edit_project_asset_path(@project, asset) %></td>
        <td><%= link_to 'Destroy', asset, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Asset', new_project_asset_path(@project) %>

app/views/assets/new.html.erb
<section class="page col-md-12">
<h2>New asset</h2>

<%= render 'form' %>
</section>

app/views/assets/show.html.erb
<section class="page col-md-12">

  <div class="showcase">
      <div class="col-md-8">
        <%= image_tag @asset.thumbnail.display_image_path, class: "thumb" unless @asset.thumbnail.nil? %>
      </div>
      <div class="col-md-4">
        <h4><%= @asset.name %></h4>
        <h6 class="text-muted"><%= link_to "#{@project.name}", project_assets_path(@project) %></h6>
        <p><small class="text-muted">Updated <%= time_ago_in_words(@asset.updated_at) %> ago</small></p>
        <div class="<%= @asset.state %> asset-badge"><%= @asset.state %></div>
        <% if @asset.experimental? %>
          <div class="experimental asset-badge">Experimental</div>
        <% end %>
        <div class="clearfix"></div>
        <% @asset.files.each do |asset_file| %>
          <%= render 'files/meta', file: asset_file %>
        <% end %>
        <% if @asset.shipable? %>
          <%= button_to "Ship it.", ship_project_asset_path(@project, @asset), class: "btn btn-success" %>
        <% end %>

      </div>
      <div class="clearfix"></div>
  </div>
  <div class="comments">
    <h5 class="text-muted">Discussion:</h5>
    <% @asset.comments.each do |comment| %>
      <%= render 'assets/comment', comment: comment %>
    <% end %>

    <%= render 'assets/new_comment_form', comment: @new_comment %>
  </div>
  <div class="clearfix"></div>
</section>