config/routes.rb
Rails.application.routes.draw do
  controller :session do
    get '/login', to: 'session#login'
    post '/session/create', to: 'session#create'
    get '/logout', to: 'session#logout'
  end

  resources :users do
    get '/notifications', to: 'notification#index', as: 'notifications'
  end

  resources :projects do
    resources :assets do
      member do
        put '/ship', to: 'assets#ship', as: 'ship'
        get '/add-files', to: 'assets#add_files'
        put '/upload', to: 'assets#upload'
      end
      resources :comments
    end
    resources :invitations do
      member do
        get '/accept', to: 'invitations#accept', as: 'accept'
      end
    end
  end


  controller 'dropbox' do
    get "/auth/dropbox_oauth2/callback", to: :link, as: :dropbox_oauth2_callback
    get "/dropbox/unlink", to: :unlink, as: :dropbox_unlink
  end

  controller 'github' do
    get "/auth/github/callback", to: :link, as: :github_oauth2_callback
    get "/github/unlink", to: :unlink, as: :github_unlink
  end

  controller 'notification' do
    get "/notification/:id/read", to: :read, as: 'notification_read'
  end

  root to: "projects#index"
end

app/views/navigation/_menu.html.erb
<% unless current_user.nil? %>
  <div class="main-menu">
    <div class="menu-button">
      <span class="glyphicon glyphicon-th-list"></span>
    </div>
    <%= link_to user_path(current_user), class: "current-user" do %>
      <%= image_tag current_user.gravatar_url(25) %>
      <h4> <%= current_user.username %> </h4>
    <% end %>
    <div class="clearfix"></div>
    <div class="actions">
      <%= link_to logout_path() do %>
        <span class="glyphicon glyphicon-log-out"></span>
      <% end %>
    </div>

    <div class="section">
      <h4>Projects</h4>
      <hr/>
      <ul>
        <% current_user.projects.each do |p| %>
          <li><%= link_to p.name, project_path(p) %></li>
        <% end %>
        <li>
          <%= link_to new_project_path, class: "muted-action" do %>
            <span class='glyphicon glyphicon-plus'></span> Add a new Project
            <% end %>
        </li>
      </ul>
    </div>
  </div>
<% end %>

app/views/navigation/_notification_menu.html.erb
<div class="notification-menu">
  <%= link_to user_notifications_path(current_user) do %>
    <span class="badge"><%= current_user.notifications.unread.count %></span>
    <span class="glyphicon glyphicon-bell"></span>
  <% end %>
</div>